### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by LordOfDeadbush**
pls

### CODE REVIEW

**Comment by LordOfDeadbush** [comment]
fixed issues, added cosmetic enhancements, made content more lgbtq snowflake friendly.

this content is powered by libtard tears

**Comment by why-does-ie-still-exist** [comment]
L+no unit tests+line length greater than 100+Not sus amogus enough

**Comment by LordOfDeadbush** [comment]
line length greater than 100 my ass

**Comment by LordOfDeadbush** [comment]
commit it nerd

**Comment by LordOfDeadbush** [comment]
do it

**Comment by why-does-ie-still-exist** [comment]
Merging...

**Comment by LordOfDeadbush** [comment]
too weak

**Comment by why-does-ie-still-exist** [comment]
Hey GH support, since Jason is so uncomfortable with this PR you can delete it for him 👍

**Pull request closed without merging**
